apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  PROXY_PASS: "http://models-backend:5001/api/books"
  NGINX_PORT: "80"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: "development"
  PORT: "5001"